spring.application.name=parkspace

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/parkspace
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

jwt.secret=KAsiMaCgP3uWLa8SLDDSFEKgkK87p6Kj1xU0c9GCNwo=
jwt.expiration=900000
app.jwt.refresh-token-expiration-days=7

app.admin.email=admin@parkspace.com
app.admin.password=Admin@123

springdoc.swagger-ui.path=/swagger-ui.html